# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wisam Zaghal
tagline:             'Something Clever'
description:         'Cras mattis consectetur purus sit amet fermentum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Made by <a href="https://twitter.com/_wzaghal" target="_blank">@_wzaghal</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Wisam Zaghal
  url:               https://twitter.com/_wzaghal
  email:             wisamzaghal@gmail.com

# Custom vars
version:             1.0.0
